import { z } from "zod";
import type { CallRow } from "../types/database";
import { supabaseService } from "./supabase.service";

const phone = z.string().regex(/^\+[1-9]\d{7,14}$/, "Use E.164 format").nullable();
const hours = z.record(z.union([z.string().regex(/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-3]):[0-5]\d$/), z.null()]));
export const configUpdateSchema = z.object({
  name: z.string().trim().min(1).max(120).optional(), industry: z.string().trim().max(120).nullable().optional(), city: z.string().trim().min(1).max(100).optional(), state: z.string().trim().min(2).max(50).optional(),
  business_phone: phone.optional(), owner_phone: phone.optional(), transfer_phone: phone.optional(), business_hours: hours.optional(), timezone: z.string().trim().min(1).max(100).optional(),
  services: z.array(z.string().trim().min(1).max(120)).max(100).optional(), service_area: z.record(z.unknown()).optional(), receptionist_greeting: z.string().trim().max(500).nullable().optional(),
  custom_instructions: z.string().trim().max(5000).nullable().optional(), pricing_rules: z.union([z.record(z.unknown()), z.array(z.unknown()), z.null()]).optional(), owner_sms_enabled: z.boolean().optional(),
}).strict();
export type ConfigUpdate = z.infer<typeof configUpdateSchema>;
export const callQuerySchema = z.object({ page: z.coerce.number().int().min(1).default(1), page_size: z.coerce.number().int().min(1).max(100).default(25), urgency: z.enum(["low","medium","high","emergency"]).optional(), status: z.string().trim().max(50).optional(), from: z.string().datetime().optional(), to: z.string().datetime().optional() });
export const monthSchema = z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/);
const configColumns = "id,name,industry,city,state,business_phone,owner_phone,business_hours,services,service_area,transfer_phone,pricing_rules,custom_instructions,receptionist_greeting,timezone,owner_sms_enabled,updated_at";

export function callDto(call: Partial<CallRow>) { return { id: call.id, caller_phone: call.caller_phone, status: call.status, started_at: call.started_at, ended_at: call.ended_at, duration_seconds: call.duration_seconds, urgency: call.urgency, summary: call.summary, intake: call.structured_intake, transcript: call.transcript, recording_url: call.recording_url, processing_status: call.processing_status }; }
export class CustomerApiService {
  constructor(private readonly client?: ReturnType<typeof supabaseService.getClient>) {}
  private get db() { return this.client ?? supabaseService.getClient(); }
  async me(businessId: string, key: { id: string; name: string; scopes: string[] }) { const { data, error } = await this.db.from("businesses").select("id,name,industry,city,state,created_at").eq("id", businessId).single(); if (error) throw new Error(error.message); return { business: data, integration: { api_key_id: key.id, name: key.name, scopes: key.scopes } }; }
  async config(businessId: string) { const { data, error } = await this.db.from("businesses").select(configColumns).eq("id", businessId).single(); if (error) throw new Error(error.message); return data; }
  async updateConfig(businessId: string, apiKeyId: string, update: ConfigUpdate) { const { data, error } = await this.db.from("businesses").update({ ...update, updated_at: new Date().toISOString() } as never).eq("id", businessId).select(configColumns).single(); if (error) throw new Error(error.message); const { error: auditError } = await this.db.from("integration_audit_logs").insert({ business_id: businessId, actor_type: "api_key", actor_id: apiKeyId, action: "config.updated", target_type: "business", target_id: businessId, metadata: { fields: Object.keys(update) } as never }); if (auditError) throw new Error(`Configuration saved but audit failed: ${auditError.message}`); return data; }
  async calls(businessId: string, query: z.infer<typeof callQuerySchema>) { let request = this.db.from("calls").select("id,caller_phone,status,started_at,ended_at,duration_seconds,urgency,summary,structured_intake,processing_status", { count: "exact" }).eq("business_id", businessId).order("started_at", { ascending: false }).range((query.page - 1) * query.page_size, query.page * query.page_size - 1); if (query.urgency) request = request.eq("urgency", query.urgency); if (query.status) request = request.eq("status", query.status); if (query.from) request = request.gte("started_at", query.from); if (query.to) request = request.lte("started_at", query.to); const { data, error, count } = await request; if (error) throw new Error(error.message); return { data: (data ?? []).map(callDto), pagination: { page: query.page, page_size: query.page_size, total: count ?? 0, has_more: query.page * query.page_size < (count ?? 0) } }; }
  async call(businessId: string, callId: string) { const { data, error } = await this.db.from("calls").select("id,caller_phone,status,started_at,ended_at,duration_seconds,urgency,summary,structured_intake,transcript,recording_url,processing_status").eq("business_id", businessId).eq("id", callId).maybeSingle(); if (error) throw new Error(error.message); return data ? callDto(data) : null; }
  async usage(businessId: string, month: string) { const start = new Date(`${month}-01T00:00:00.000Z`); const end = new Date(start); end.setUTCMonth(end.getUTCMonth()+1); const { data, error } = await this.db.from("calls").select("status,duration_seconds,analysis_completed_at,owner_notified_at").eq("business_id", businessId).gte("started_at", start.toISOString()).lt("started_at", end.toISOString()); if (error) throw new Error(error.message); const rows=data??[]; const seconds=rows.reduce((n,c)=>n+(c.duration_seconds??0),0); return { period:{start:start.toISOString(),end:end.toISOString()}, inbound_calls:rows.length, completed_calls:rows.filter(c=>c.status==="ended").length, total_call_seconds:seconds, total_call_minutes:Math.ceil(seconds/60), analyzed_calls:rows.filter(c=>c.analysis_completed_at).length, owner_notifications_generated:rows.filter(c=>c.owner_notified_at).length }; }
  async readiness(businessId: string) { const { data, error } = await this.db.from("businesses").select("vapi_phone_number_id,owner_phone,owner_sms_enabled,name,city,state,services,business_hours,timezone").eq("id",businessId).single(); if(error)throw new Error(error.message); const missing=[!data.name&&"name",!data.city&&"city",!data.state&&"state",!data.services&&"services",!data.business_hours&&"business_hours",!data.timezone&&"timezone"].filter(Boolean); return { ai_phone_line:data.vapi_phone_number_id?"active":"setup_required",owner_notifications:data.owner_phone&&data.owner_sms_enabled?"active":"setup_required",configuration:missing.length?"incomplete":"complete",missing_configuration:missing }; }
}
export const customerApiService = new CustomerApiService();
