import assert from "node:assert/strict";import test from "node:test";import { callDto, callQuerySchema, configUpdateSchema, CustomerApiService } from "./customer-api.service";
test("config API allowlists customer fields and rejects provider/internal fields",()=>{assert.equal(configUpdateSchema.parse({name:"Business A",owner_phone:"+13125550100"}).name,"Business A");for(const field of ["business_id","vapi_phone_number_id","vapi_assistant_id","key_hash","processing_status"]){assert.throws(()=>configUpdateSchema.parse({[field]:"forbidden"}));}});
test("call query validates pagination and supported filters",()=>{assert.deepEqual(callQuerySchema.parse({page:"2",page_size:"10",urgency:"high"}),{page:2,page_size:10,urgency:"high"});assert.throws(()=>callQuerySchema.parse({page_size:"101"}));});
test("call DTO is lead-friendly and excludes provider and tenant internals",()=>{const dto=callDto({id:"call-a",business_id:"business-a",vapi_call_id:"provider-call",caller_phone:"+13125550100",structured_intake:{reason_for_call:"Repair"},processing_status:"notified"});assert.equal(dto.id,"call-a");assert.deepEqual(dto.intake,{reason_for_call:"Repair"});assert.equal("business_id" in dto,false);assert.equal("vapi_call_id" in dto,false);});

class TenantDb { calls=[{id:"call-a",business_id:"business-a",caller_phone:"A"},{id:"call-b",business_id:"business-b",caller_phone:"B"}]; businesses=[{id:"business-a",name:"A"},{id:"business-b",name:"B"}]; from(table:string){return new TenantQuery(this,table);} }
class TenantQuery {private filters:Array<[string,unknown]>=[];private values:any;private operation="select";constructor(private db:TenantDb,private table:string){}select(){return this;}update(v:any){this.operation="update";this.values=v;return this;}insert(){this.operation="insert";return this;}eq(k:string,v:unknown){this.filters.push([k,v]);return this;}gte(){return this;}lt(){return this;}order(){return this;}range(){return this;}async maybeSingle(){const result=await this.run();return{...result,data:Array.isArray(result.data)?result.data[0]??null:null};}async single(){const result=await this.run();return{...result,data:Array.isArray(result.data)?result.data[0]:result.data};}then(a:any,b:any):any{return this.run().then(a,b);}private async run():Promise<any>{if(this.operation==="insert")return{data:null,error:null};const rows=(this.table==="calls"?this.db.calls:this.db.businesses).filter(row=>this.filters.every(([k,v])=>(row as any)[k]===v));if(this.operation==="update")rows.forEach(row=>Object.assign(row,this.values));return{data:rows,error:null,count:rows.length};}}
test("tenant-scoped call reads and lists cannot cross from Business A to Business B",async()=>{const db=new TenantDb();const service=new CustomerApiService(db as any);assert.equal(await service.call("business-a","call-b"),null);assert.equal((await service.call("business-a","call-a"))?.caller_phone,"A");const list=await service.calls("business-a",callQuerySchema.parse({}));assert.equal(list.data.length,1);assert.equal(list.data[0].id,"call-a");});
test("tenant-scoped configuration mutation cannot change Business B",async()=>{const db=new TenantDb();const service=new CustomerApiService(db as any);await service.updateConfig("business-a","key-a",{name:"A updated"});assert.equal(db.businesses[0].name,"A updated");assert.equal(db.businesses[1].name,"B");});
