import { createCipheriv, createDecipheriv, createHmac, randomBytes, randomUUID } from "node:crypto";
import { env } from "../config/env";
import type { CallRow, Json, WebhookDeliveryRow } from "../types/database";
import { findBusinessForOperator as findBusinessByIdentifier } from "./operator-business-resolution.service";
import { logger } from "./logger.service";
import { supabaseService } from "./supabase.service";

export type WebhookEventType = "call.completed" | "call.analysis_completed";
const encryptionKey = (): Buffer => { const key = Buffer.from(env.webhook.encryptionKey ?? "", "base64"); if (key.length !== 32) throw new Error("WEBHOOK_SECRET_ENCRYPTION_KEY must be a base64-encoded 32-byte key."); return key; };
export function encryptSecret(secret: string): string { const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv); const ciphertext=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]); return [iv,cipher.getAuthTag(),ciphertext].map(x=>x.toString("base64url")).join("."); }
export function decryptSecret(value: string): string { const [iv,tag,ciphertext]=value.split(".").map(x=>Buffer.from(x,"base64url")); if(!iv||!tag||!ciphertext)throw new Error("Invalid encrypted webhook secret."); const decipher=createDecipheriv("aes-256-gcm",encryptionKey(),iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(ciphertext),decipher.final()]).toString("utf8"); }
export function signWebhook(secret:string,timestamp:string,body:string):string{return `v1=${createHmac("sha256",secret).update(`${timestamp}.${body}`).digest("hex")}`;}
export function safeCallPayload(call: Partial<CallRow>) { return { id:call.id,caller_phone:call.caller_phone,status:call.status,started_at:call.started_at,ended_at:call.ended_at,duration_seconds:call.duration_seconds,summary:call.summary,intake:call.structured_intake,urgency:call.urgency,processing_status:call.processing_status }; }
export function createEventEnvelope(id:string,eventType:WebhookEventType,createdAt:string,call:Partial<CallRow>){return{id,type:eventType,created_at:createdAt,api_version:"2026-08-27",data:{object:safeCallPayload(call)}};}
export function webhookRetryState(attemptCount:number,now=Date.now(),maxAttempts=env.webhook.maxAttempts){const exhausted=attemptCount>=maxAttempts;const delaySeconds=Math.min(3600,30*2**Math.max(0,attemptCount-1));return{status:exhausted?"failed" as const:"retrying" as const,next_attempt_at:new Date(now+delaySeconds*1000).toISOString()};}

export class WebhookService {
  private get db(){return supabaseService.getClient();}
  async createEndpoint(businessIdentifier:string,url:string,name="Default",eventTypes:WebhookEventType[]=["call.completed","call.analysis_completed"]){const parsed=new URL(url);if(parsed.protocol!=="https:")throw new Error("Webhook URL must use HTTPS.");const business=await findBusinessByIdentifier(businessIdentifier);const secret=`whsec_${randomBytes(32).toString("base64url")}`;const {data,error}=await this.db.from("webhook_endpoints").insert({business_id:business.id,name,url,enabled:true,event_types:eventTypes,secret_prefix:secret.slice(0,14),secret_ciphertext:encryptSecret(secret)}).select("id,business_id,name,url,enabled,event_types,secret_prefix,created_at").single();if(error)throw new Error(error.message);await this.audit(business.id,"webhook_endpoint.created",data.id,{url,event_types:eventTypes});return{signing_secret:secret,endpoint:data};}
  async rotateSecret(endpointId:string){const secret=`whsec_${randomBytes(32).toString("base64url")}`;const {data,error}=await this.db.from("webhook_endpoints").update({secret_prefix:secret.slice(0,14),secret_ciphertext:encryptSecret(secret),updated_at:new Date().toISOString()}).eq("id",endpointId).select("id,business_id,secret_prefix").maybeSingle();if(error||!data)throw new Error(error?.message??"Webhook endpoint not found.");await this.audit(data.business_id,"webhook_endpoint.secret_rotated",data.id);return{signing_secret:secret,endpoint:data};}
  async enqueue(eventType:WebhookEventType,callId:string){const {data:call,error:callError}=await this.db.from("calls").select("id,business_id,caller_phone,status,started_at,ended_at,duration_seconds,summary,structured_intake,urgency,processing_status").eq("id",callId).single();if(callError||!call)throw new Error(callError?.message??"Call not found");const eventId=randomUUID();const createdAt=new Date().toISOString();const payload=createEventEnvelope(eventId,eventType,createdAt,call);const {data:event,error:eventError}=await this.db.from("webhook_events").upsert({id:eventId,business_id:call.business_id,event_type:eventType,object_type:"call",object_id:call.id,api_version:"2026-08-27",payload:payload as Json},{onConflict:"business_id,event_type,object_type,object_id",ignoreDuplicates:true}).select("id,business_id").maybeSingle();if(eventError)throw new Error(eventError.message);let persisted=event;if(!persisted){const result=await this.db.from("webhook_events").select("id,business_id").eq("business_id",call.business_id).eq("event_type",eventType).eq("object_type","call").eq("object_id",call.id).single();if(result.error)throw new Error(result.error.message);persisted=result.data;}const {data:endpoints,error:endpointError}=await this.db.from("webhook_endpoints").select("id").eq("business_id",call.business_id).eq("enabled",true).contains("event_types",[eventType]);if(endpointError)throw new Error(endpointError.message);if(endpoints?.length){const {error}=await this.db.from("webhook_deliveries").upsert(endpoints.map(e=>({business_id:call.business_id,endpoint_id:e.id,event_id:persisted.id})),{onConflict:"endpoint_id,event_id",ignoreDuplicates:true});if(error)throw new Error(error.message);}return persisted.id;}
  async deliverDue(batchSize=25,send:typeof fetch=fetch){const {data,error}=await this.db.rpc("claim_webhook_deliveries",{batch_size:batchSize});if(error)throw new Error(error.message);let succeeded=0,failed=0;for(const delivery of data??[]){try{await this.deliverOne(delivery,send);succeeded++;}catch(cause){failed++;logger.warn("Outbound webhook delivery failed",{deliveryId:delivery.id,error:cause instanceof Error?cause.message:"Unknown error"});}}return{claimed:data?.length??0,succeeded,failed};}
  private async deliverOne(delivery:WebhookDeliveryRow,send:typeof fetch){const {data,error}=await this.db.from("webhook_deliveries").select("*, webhook_endpoints(*), webhook_events(*)").eq("id",delivery.id).single();if(error||!data)throw new Error(error?.message??"Delivery not found");const endpoint=data.webhook_endpoints;const event=data.webhook_events;const body=JSON.stringify(event.payload);const timestamp=Math.floor(Date.now()/1000).toString();let response:Response;try{response=await send(endpoint.url,{method:"POST",headers:{"content-type":"application/json","user-agent":"Scalehouse-Webhooks/1.0","x-scalehouse-event-id":event.id,"x-scalehouse-timestamp":timestamp,"x-scalehouse-signature":signWebhook(decryptSecret(endpoint.secret_ciphertext),timestamp,body)},body,signal:AbortSignal.timeout(env.webhook.timeoutMs)});}catch(cause){await this.recordFailure(delivery,cause instanceof Error?cause.message:"Network error");throw cause;}if(response.ok){await this.db.from("webhook_deliveries").update({status:"succeeded",http_status:response.status,delivered_at:new Date().toISOString(),error_summary:null,updated_at:new Date().toISOString()}).eq("id",delivery.id);return;}await this.recordFailure(delivery,`HTTP ${response.status}`,response.status);throw new Error(`HTTP ${response.status}`);}
  private async recordFailure(delivery:WebhookDeliveryRow,message:string,httpStatus?:number){await this.db.from("webhook_deliveries").update({...webhookRetryState(delivery.attempt_count),http_status:httpStatus??null,error_summary:message.slice(0,500),updated_at:new Date().toISOString()}).eq("id",delivery.id);}
  private async audit(businessId:string,action:string,targetId:string,metadata:Record<string,unknown>={}){const {error}=await this.db.from("integration_audit_logs").insert({business_id:businessId,actor_type:"operator",action,target_type:"webhook_endpoint",target_id:targetId,metadata:metadata as never});if(error)throw new Error(`Audit log failed: ${error.message}`);}
}
export const webhookService=new WebhookService();
export async function enqueueWebhookSafely(type:WebhookEventType,callId:string){try{await webhookService.enqueue(type,callId);}catch(cause){logger.error("Webhook event enqueue failed",{callId,eventType:type,error:cause instanceof Error?cause.message:"Unknown error"});}}
